# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- features/

pool: "Requiem Labs"

steps:
- task: Pester@10
  inputs:
    scriptFolder: '$(System.DefaultWorkingDirectory)\test\*'
    resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
    usePSCore: False
