# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- features/*
- master

pool: "Requiem Labs"

steps:
- task: PowerShell@2
  displayName: "Check Pester Install"
  inputs:
    targetType: 'inline'
    script: |
      $modules = Get-Module -list
      if ($modules.Name -notcontains 'pester') {
          Install-Module -Name Pester -Force -SkipPublisherCheck
      }

