# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- features/*
- master

pool: "Requiem Labs"

variables:
  # temporary, we will get this from SimpleSemVer eventually
  major: '0'
  minor: '2'
  patch: '0'
  prerelease: '-alpha1-'
  buildnum: $[counter(variables['patch'], 0)]
  version: '$(MAJOR).$(MINOR).$(PATCH)$(PRERELEASE)$(BUILDNUM)'

stages:
- stage: SBN
  displayName: Prebuild work
  jobs:
  - job: SBN
    displayName: Set build number
    steps:
    - powershell: |
          echo "##vso[build.updatebuildnumber]$(VERSION)"
      name: SBN
      displayName: Set build number to version number

- stage: Tests
  displayName: Run tests
  jobs:
  - job: PrepEnv
    displayName: Prepare Environment
    steps:
    - checkout: none
    - task: PowerShell@2
      displayName: 'Install Pester'
      inputs:
        filePath: 'AzureHelperFunctions/InstallPester.ps1'
        failOnStderr: true
        workingDirectory: '$(Pipeline.Workspace)/s'
  - job: RunPester
    dependsOn: PrepEnv
    displayName: Pester Tests
    steps:
    - checkout: none
    - task: PowerShell@2
      displayName: 'Run Pester Tests'
      inputs:
        filePath: 'AzureHelperFunctions/RunPester.ps1'
        failOnStderr: true
        workingDirectory: '$(Pipeline.Workspace)/s'
    - task: PublishTestResults@2
      displayName: 'Upload Test Results'
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '**/Test*.xml'
        searchFolder: '$(Common.TestResultsDirectory)'
        failTaskOnFailedTests: true
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '**/CodeCov.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src'