# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- features/*
- master

pool: "Requiem Labs"

variables:
  # temporary, we will get this from SimpleSemVer eventually
  major: '0'
  minor: '2'
  patch: '0'
  prerelease: '-alpha1-'
  buildnum: $[counter(variables['patch'], 0)]
  version: '$(MAJOR).$(MINOR).$(PATCH).$(PRERELEASE)$(BUILDNUM)'

steps:
- powershell: |
      echo "##vso[build.updatebuildnumber]$(MAJOR).$(MINOR).$(PATCH).$(BUILDNUM)"
  name: SMBN
  displayName: Set Build Name

- task: PowerShell@2
  displayName: 'Install Pester'
  inputs:
    filePath: 'AzureHelperFunctions/InstallPester.ps1'
    failOnStderr: true
    workingDirectory: '$(Pipeline.Workspace)/s'

- task: PowerShell@2
  displayName: 'Run Pester Tests'
  inputs:
    filePath: 'AzureHelperFunctions/RunPester.ps1'
    failOnStderr: true
    workingDirectory: '$(Pipeline.Workspace)/s'

- task: PublishTestResults@2
  displayName: 'Upload Test Results'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST*.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    failTaskOnFailedTests: true